android.useAndroidX=true
android.enableJetifier=true

# ???????????  ????? Gradle ?????????????? ?????????? ?? JDK 17:
# ????? ???????????? ???? ? Temurin 17, ???? ?? ??????????
# org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk-17
org.gradle.java.installations.auto-detect=true
org.gradle.java.installations.auto-download=true
