spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/minitasker
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

logging:
  level:
    root: INFO
    com.example.minitasker: DEBUG

minitasker:
  security:
    jwt-secret: change-me-please-change-me-please-change-me-please
    jwt-expiration-minutes: 60
  attachments-dir: /data/attachments

server:
  address: 0.0.0.0
  port: 8080
